ALTER TABLE Veiculo DROP CONSTRAINT FKVeiculo652748;
ALTER TABLE Reserva DROP CONSTRAINT FKReserva520514;
ALTER TABLE Reserva DROP CONSTRAINT FKReserva762773;
ALTER TABLE Pagamento DROP CONSTRAINT FKPagamento765087;
ALTER TABLE Manutencao DROP CONSTRAINT FKManutencao178953;
ALTER TABLE Historico_Utilizacao DROP CONSTRAINT FKHistorico_950807;
ALTER TABLE Historico_Utilizacao DROP CONSTRAINT FKHistorico_193067;
ALTER TABLE Manutencao_Vaga DROP CONSTRAINT FKManutencao996824;
ALTER TABLE Manutencao_Vaga DROP CONSTRAINT FKManutencao583198;

DROP TABLE Manutencao_Vaga;
DROP TABLE Historico_Utilizacao;
DROP TABLE Manutencao;
DROP TABLE Funcionario;
DROP TABLE Pagamento;
DROP TABLE Reserva;
DROP TABLE Vaga;
DROP TABLE Cliente;
DROP TABLE Veiculo;